#cloud-config
users:
  - name: ubuntu
    lock_passwd: true
  - name: system.administrator
    gecos: System Administrator
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: true
    ssh_authorized_keys:
        - ${ssh_public_key}

# update on the first boot
package_update: true
package_upgrade: true
# install packages during the first boot
packages:
 - htop
 - vim
 - tmux
 - lvm2
 - net-tools
 - tree
 - atop
 - iotop
 - jq

write_files:
  - path: /etc/nginx/sites-enabled/proxy.conf
    content: |
      upstream backend {
          # replace ip and port with appropriate values
          server 10.0.1.47:32100;
      }    
      server {
          listen 8080;
      
          location / {
              proxy_pass http://backend;
      
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

# For bastion/VPN service configuration - SSH will use alternative port 32100/tcp
runcmd:
  - |
    sed -i 's/^#Port 22/Port 32100/' /etc/ssh/sshd_config
    systemctl restart ssh
    apt install -y nginx
    rm /etc/nginx/sites-enabled/default
    systemctl restart nginx
    
