# -*- mode: ruby -*-
# vi: set ft=ruby :

## раскоментируйте если вам не доступен ванльный репозиторий vagrant
# ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
## конфиг стенда
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 600
  config.vm.box_download_insecure=true
  config.vm.synced_folder "conf/", "/opt/conf", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "../helm/", "/opt/helm", owner: "vagrant", group: "vagrant"
  config.vm.provision "init", type: "shell", path: "lib/init.sh"
  
  config.vm.define "k3s" do |config|
    config.vm.hostname = "k3s"
    config.vm.network "private_network", ip: "192.168.100.100"
    config.vm.disk :disk, size: "30GB", primary: true
    
    config.vm.provider "virtualbox" do |server|
      server.name = "k3s"
      server.cpus = 2
      server.memory = "2048"
    end
    config.vm.provision "k3s", type: "shell", path: "lib/k3s.sh"
    config.vm.provision "helm", type: "shell", path: "lib/helm.sh"

    ## if you wan to deploy jenkins via yaml manifests
    #config.vm.provision "k8s-yaml", type: "shell", path: "lib/jenkins-yaml.sh"

    ## if you wan to deploy jenkins via helm manifests
    #config.vm.provision "k8s-yaml", type: "shell", path: "lib/jenkins-helm.sh"

  end

end