apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.jenkins.storage.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.jenkins.storage.pv.storageClassName }}
  claimRef:
    name: {{ .Values.jenkins.storage.pvc.name }}
    namespace: {{ .Values.namespace }}
  capacity:
    storage: {{ .Values.jenkins.storage.size }}
  accessModes:
    - {{ .Values.jenkins.storage.accessMode }}
  hostPath:
    path: {{ .Values.jenkins.storage.pv.hostPath }}
