name: Terraform Check Workflow

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'Terraform version to use'
        required: true
        type: string
      working_directory:
        description: 'Working directory for Terraform commands'
        required: true
        type: string

jobs:
  terraform-check:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          audience: sts.amazonaws.com.cn
#          aws-region: 'eu-west-1' # ${{ inputs.aws-region-id }}
#          role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
#          role-session-name: GitHubActions

      - name: Initialize Terraform
        working-directory: ${{ inputs.working_directory }}
        run: terraform init

      - name: Check Terraform format
        working-directory: ${{ inputs.working_directory }}
        run: terraform fmt -check
