#cloud-config
hostname: ${hostname}
manage_etc_hosts: true
users:
  - name: ubuntu
    lock_passwd: true
  - name: system.administrator
    gecos: System Administrator
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: true
    ssh_authorized_keys:
        - ${ssh_public_key}

# update on the first boot
package_update: true
package_upgrade: true
# install packages during the first boot
packages:
 - htop
 - vim
 - tmux
 - lvm2
 - net-tools
 - tree
 - atop
 - iotop
 - jq


# For k3s deployment from the begging - just after instance creation
# And grafana cloud monitoring
runcmd:
  - |
    sleep 30
    ufw disable
    curl -sfL https://get.k3s.io | sh -s - server --kube-apiserver-arg "bind-address=0.0.0.0"
    chmod 644 /etc/rancher/k3s/k3s.yaml
    cp /etc/rancher/k3s/k3s.yaml /home/system.administrator/.kube/conf
    chown system.administrator:system.administrator /home/system.administrator/.kube/conf
    apt install -y bash-completion git
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    sudo apt  install -y apt-transport-https
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt update
    sudo apt install -y helm
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    ## Temp replaced jenkins with wordpress
    # mkdir -p /opt/conf/task_4
    # git clone -b task_4 https://github.com/kazarin-ka/rsschool-devops-course-tasks.git /opt/conf/task_4
    # helm install jenkins /opt/conf/task_4/helm/jenkins-helm-chart --set jenkins.service.nodePort=32000
    mkdir -p /opt/helm
    git clone https://github.com/kazarin-ka/rs-school_task-5.git /opt/helm
    helm install my-wordpress /opt/helm/wordpress --set wordpress.service.nodePort=32000
